### ISSUE TITLE
Opensea sweep feature

### ISSUE THREAD

**Issue by doopie-art** [kenryu42/ethereum-nft-sales-bot#21]
I'm encountering sweeps completed by Opensea which when detected are appearing with mis-information. 

e.g. A sweep of various tokens on a single contract

Correctly says the Qty and 'SWEPT', but the total sales price is incorrect. It is likely showing a price paid for one of the tokens.
The 'From' and 'To' only appears as if it's one token sold.

I notice in the src code that the embedded object appears differently for sweeps when the tx is from 'gem', 'genie' or 'blurSwap'. I suspect the Opensea sweep feature is not yet supported?

**Comment by kenryu42** [comment]
Sweep feature in Opensea is supported.
Please provide the `transaction hash` so that I could debug.

**Comment by doopie-art** [comment]
0x08b5e00b59dcb9a471bffd089cec33b5875a4e5e23cfa821635b8b6685c945e8

Thanks

**Comment by kenryu42** [comment]
The bug has been fixed in the latest release of the npm package. You can install the updated package by running `npm install enft`.

This release is a `breaking change`, so be sure to check out the updated [documentation](https://github.com/kenryu42/ethereum-nft-sales-bot#readme).

If you encounter any further issues or have any questions, feel free to reach out.
